version: '3.8'

services:
  bot_service:
    build: ./bot_service
    env_file:
      - .env
    environment:
      - ANALYSIS_SERVICE_URL=http://ai_service:5000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      ai_service:
        condition: service_started
      rabbitmq:
        condition: service_started

  ai_service:
    build: ai_service
    ports:
      - "5000:5000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/docs"]
      interval: 120s
      timeout: 5s
      retries: 1

  database_service:
    build: ./database_service
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - POSTGRES_HOST=postgres_db
    depends_on:
      postgres_db:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
      - "8000:8000"

  postgres_db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 120s
      timeout: 5s
      retries: 1
volumes:
  postgres_data: